# Generated by Django 4.0.1 on 2022-01-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default=None, max_length=50)),
                ('lastname', models.CharField(default=None, max_length=50)),
                ('emailid', models.EmailField(max_length=254, unique=True)),
                ('password', models.TextField(max_length=32)),
            ],
        ),
    ]
