# Generated by Django 3.2.6 on 2022-01-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='name',
        ),
        migrations.AddField(
            model_name='users',
            name='firstname',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='users',
            name='lastname',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
