# Generated by Django 3.2.6 on 2022-01-17 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_auto_20220117_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='email',
            new_name='emailid',
        ),
    ]
